#
# Makefile for the CH7025/7026 TV Encoder.
#
obj-$(CONFIG_CH7025_7026_TVOUT)			+= ch7025.o
obj-$(CONFIG_CH7025_7026_TVOUT_YPBPR)	+= ch7025_ypbpr.o
obj-$(CONFIG_CH7025_7026_TVOUT_CVBS)	+= ch7025_cvbs.o