/* Automatically generated by kernel/timeconst.pl */
/* Conversion constants for HZ == 100 */

#ifndef KERNEL_TIMECONST_H
#define KERNEL_TIMECONST_H

#include <linux/param.h>
#include <linux/types.h>

#if HZ != 100
#error "kernel/timeconst.h has the wrong HZ value!"
#endif

#define HZ_TO_MSEC_MUL32        U64_C(0xa0000000)
#define HZ_TO_MSEC_ADJ32        U64_C(0x0)
#define HZ_TO_MSEC_SHR32        28
#define HZ_TO_MSEC_NUM          U64_C(10)
#define HZ_TO_MSEC_DEN          U64_C(1)
#define MSEC_TO_HZ_MUL32        U64_C(0xcccccccd)
#define MSEC_TO_HZ_ADJ32        U64_C(0x733333333)
#define MSEC_TO_HZ_SHR32        35
#define MSEC_TO_HZ_NUM          U64_C(1)
#define MSEC_TO_HZ_DEN          U64_C(10)
#define HZ_TO_USEC_MUL32        U64_C(0x9c400000)
#define HZ_TO_USEC_ADJ32        U64_C(0x0)
#define HZ_TO_USEC_SHR32        18
#define HZ_TO_USEC_NUM          U64_C(10000)
#define HZ_TO_USEC_DEN          U64_C(1)
#define USEC_TO_HZ_MUL32        U64_C(0xd1b71759)
#define USEC_TO_HZ_ADJ32        U64_C(0x1fff2e48e8a7)
#define USEC_TO_HZ_SHR32        45
#define USEC_TO_HZ_NUM          U64_C(1)
#define USEC_TO_HZ_DEN          U64_C(10000)

#endif /* KERNEL_TIMECONST_H */
